runtime: python310
entrypoint: gunicorn -b :$PORT webApp:app

instance_class: F4_1G

automatic_scaling:
  target_cpu_utilization: 0.80
  min_instances: 1
  max_instances: 20

#basic_scaling:
#  max_instances: 5
#  idle_timeout: 10m

env_variables:
  OPENAI_API_KEY: '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'
  BUCKET_NAME: 'catboxv1'

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
- url: /(.*)
  static_files: dist/\1
  upload: dist/(.*)

